### ISSUE TITLE
UNIT_TEST="1" is too slow and finish build by timeout issue

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#251]
I proposal to fix it just add a unit_test to modules changed in a PR and depends.

Example module changed:

| Module | Depends | Changed? |
| --- | --- | --- |
| module1 | module2 | Yes |
| module2 | module3 | No |
| module3 | base | No |
| module4 | sale | No |
| module5 | module1 | No |
| module6 | purchase | No |

If UNIT_TEST=="1" then will create databases for:
`-i module1` because is the module changed.
`-i module2` because is depends of module1
`-i module3` because is depends of module2, and module2 is depends of module1
`-i module5` because there is depends to module1

But won't create database for other ones (module5 and module6)

What do you think?

Currently, many projects avoid use UNIT_TEST="1" because is too slow, but is very useful.
This change could increase the use of this feature and have full result.

**Comment by dreispt** [comment]
It makes sense to "unit test" only modules changes in the PR.
And new that capability is there, so go ahead.

**Comment by moylop260** [comment]
@dreispt 
Thank for you feedback!

**Comment by ajite** [comment]
Would not that make the coveralls result lower? Coveralls will think that you have removed some test when you actually just did not run them.

**Comment by moylop260** [comment]
@ajite 
The result of coveralls is when `TESTS="1"`
`UNIT_TEST="1"` should be a splitted environment.

```yaml
env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"  # coveralls here
  - UNIT_TEST="1" ODOO_REPO="odoo/odoo"  # without coveralls
```
