### ISSUE TITLE
Running odoo standard tests (JS tests included)?

### ISSUE THREAD

**Issue by oerp-odoo** [OCA/maintainer-quality-tools#565]
Currently I have this configuration of `.travis.yml`:

```yml
language: python

python:
  - "3.5"

sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0"
  - PHANTOMJS_VERSION="latest"
  matrix:
  - TESTS="1" ODOO_REPO="odoo/odoo"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
```
So it does run my modules tests, but Odoo standard modules tests are not run. Is there a way to do that? For example using `odoo.sh` it will run all tests for modules that are installed (including JS tests).
