### ISSUE TITLE
pre-commit: need to pin flake8

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintainer-quality-tools#664]
It looks like the default flake8 pre-commit hook is not pinning the flake8 version. We may have issues with the new flake8 release. This a way to pin it:

```
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
```
