### ISSUE TITLE
EXCLUDE does not exclude a module from being tested by travis_run_tests If such module is found in the git repo

### ISSUE THREAD

**Issue by gfunosas** [OCA/maintainer-quality-tools#709]
## Module
[maintainer-quality-tools](https://github.com/OCA/maintainer-quality-tools)

## Describe the bug
In a repo with a CI testing we physically find placed two odoo modules: A and B. Module B inherits from module A. 

In this case, the [`tested_addons_list` variable](https://github.com/OCA/maintainer-quality-tools/blob/master/travis/test_server.py#L349) would become a list of the two modules ([module A, module B]). 
If we want git CI to test just the module B, we would use the gitlab-ci variable "EXCLUDE" to exclude module A from being tested. 
This logic leaves the variable `tested_addons_list` just with module B, so we can see in the pipeline logs:

```
Testing ['<module B>']:
unbuffer coverage run /root/ocb-12.0_2020-11-13/odoo-bin -d openerp_test --db-filter=^openerp_test$ --stop-after-init --log-level info --log-handler openerp.tools.yaml_import:DEBUG --test-enable --init <module B>
``` 
Even with the pipeline executing this command, tests from module A end up executed within the pipeline altogether with the ones from B.

## To Reproduce
1. Add two odoo modules to a gitlab repo, B depending on A in its manifest. 
2. In a new branch, add a `.gitlab-ci.yml` with:

```
- image: python3.8
- stages: 
  - test
- variables:
  - EXCLUDE: "<module A>"
``` 

And within test stage definition

```
- variables:
    LINT_CHECK: "0"
    TESTS: "1"
- script:
    - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true
``` 

3. Commit the changes and push them on the branch.
4. Look at the pipeline result. 

**Expected behavior**
Tests from module A are not tested on git CI pipeline (but they are). 

**Additional context**
  - VERSION: "12.0"
  - ODOO_BRANCH: "12.0_2020-11-13"
